### ISSUE TITLE
Cannot find module '/server/dist/app/index.js'

### ISSUE THREAD

**Issue by chenkie** [darkcl/simple-upload#1]
Hi there, thanks for your project!

After running `docker-compose up` I'm seeing the following:

```bash
Debugger listening on ws://0.0.0.0:5858/fa8e45d7-495b-4d26-a253-519ac4c3a26d
api_1  | For help see https://nodejs.org/en/docs/inspector
api_1  | module.js:549
api_1  |     throw err;
api_1  |     ^
api_1  | 
api_1  | Error: Cannot find module '/server/dist/app/index.js'
api_1  |     at Function.Module._resolveFilename (module.js:547:15)
api_1  |     at Function.Module._load (module.js:474:25)
api_1  |     at Function.Module.runMain (module.js:693:10)
api_1  |     at startup (bootstrap_node.js:191:16)
api_1  |     at bootstrap_node.js:612:3
```

Thanks for your help!

**Comment by darkcl** [comment]
Should work on latest commit, forget to remove `volumes` in `docker-compose.yml` 😆

**Comment by chenkie** [comment]
Thanks!
